# class ChunkManager:
#     def get_current_chunk(self):
#         ...

#     def get_chunk_for_timestamp(self, timestamp):
#         ...

#     def create_chunk(self, timestamp):
#         ...

#     def list_chunks(self, start, end):
#         ...

#     def close_chunk(self, chunk):
#         ...