class DuckDBDatabase:
    def create(self) -> None:
        ...

    def exists(self) -> bool:
        ...

    def initialize(self) -> None:
        ...

    def delete(self) -> None:
        ...

    def vacuum(self) -> None:
        ...