"""empty message

Revision ID: 7f41c03ee0de
Revises: 
Create Date: 2026-08-08 11:08:51.709225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from observa.common.model.base import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = '7f41c03ee0de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('accepted_terms_of_service_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('accepted_terms_of_service_ip', sa.String(), nullable=True),
    sa.Column('blocked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('modified_at', UTCDateTime(), nullable=True),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_table('accounts',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('modified_at', UTCDateTime(), nullable=True),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('accounts_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('accounts_user_id_key'))
    )
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_accounts_deleted_at'), 'accounts', ['deleted_at'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', UTCDateTime(), nullable=False),
    sa.Column('revoked_at', UTCDateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('modified_at', UTCDateTime(), nullable=True),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('auth_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_sessions_pkey'))
    )
    op.create_index(op.f('ix_auth_sessions_created_at'), 'auth_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_deleted_at'), 'auth_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('modified_at', UTCDateTime(), nullable=True),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('teams_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('teams_pkey')),
    sa.UniqueConstraint('account_id', 'slug', name='uq_team_account_slug')
    )
    op.create_index(op.f('ix_teams_account_id'), 'teams', ['account_id'], unique=False)
    op.create_index(op.f('ix_teams_created_at'), 'teams', ['created_at'], unique=False)
    op.create_index(op.f('ix_teams_deleted_at'), 'teams', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_teams_status'), 'teams', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('first_event', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('modified_at', UTCDateTime(), nullable=True),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.CheckConstraint('\n            (account_id IS NOT NULL AND team_id IS NULL)\n            OR\n            (account_id IS NULL AND team_id IS NOT NULL)\n            ', name=op.f('projects_ck_project_single_owner_check')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('projects_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('projects_team_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey')),
    sa.UniqueConstraint('account_id', 'slug', name=op.f('projects_account_id_slug_key')),
    sa.UniqueConstraint('team_id', 'slug', name=op.f('projects_team_id_slug_key'))
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('joined_at', UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('modified_at', UTCDateTime(), nullable=True),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('team_members_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('team_members_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('team_members_pkey')),
    sa.UniqueConstraint('team_id', 'account_id', name='uq_team_member')
    )
    op.create_index(op.f('ix_team_members_account_id'), 'team_members', ['account_id'], unique=False)
    op.create_index(op.f('ix_team_members_created_at'), 'team_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_team_members_deleted_at'), 'team_members', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_team_members_joined_at'), 'team_members', ['joined_at'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_table('alerts',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('alert_type', sa.Enum('METRIC', 'LOG', 'TRACE', name='alerttype'), nullable=False),
    sa.Column('query', sa.String(length=1000), nullable=False),
    sa.Column('condition', sa.Enum('GREATER_THAN', 'GREATER_THAN_OR_EQUAL', 'LESS_THAN', 'LESS_THAN_OR_EQUAL', 'EQUAL', 'NOT_EQUAL', name='alertcondition'), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='alertstatus'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('modified_at', UTCDateTime(), nullable=True),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('alerts_created_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('alerts_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey')),
    sa.UniqueConstraint('project_id', 'alert_type', 'name', name='uq_alert_project_type_name')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_deleted_at'), 'alerts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_alerts_project_id'), 'alerts', ['project_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('project_ingestion_keys',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_account_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('public_key', sa.String(length=32), nullable=False),
    sa.Column('secret_key', sa.String(length=32), nullable=False),
    sa.Column('roles', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('rate_limit_count', sa.Integer(), nullable=True),
    sa.Column('rate_limit_window', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('use_case', sa.String(length=32), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('modified_at', UTCDateTime(), nullable=True),
    sa.Column('deleted_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['accounts.id'], name=op.f('project_ingestion_keys_created_by_account_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_ingestion_keys_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_ingestion_keys_pkey')),
    sa.UniqueConstraint('public_key', name='uq_project_key_public_key'),
    sa.UniqueConstraint('secret_key', name='uq_project_key_secret_key')
    )
    op.create_index(op.f('ix_project_ingestion_keys_created_at'), 'project_ingestion_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_ingestion_keys_created_by_account_id'), 'project_ingestion_keys', ['created_by_account_id'], unique=False)
    op.create_index(op.f('ix_project_ingestion_keys_deleted_at'), 'project_ingestion_keys', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_project_ingestion_keys_project_id'), 'project_ingestion_keys', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_ingestion_keys_status'), 'project_ingestion_keys', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_ingestion_keys_status'), table_name='project_ingestion_keys')
    op.drop_index(op.f('ix_project_ingestion_keys_project_id'), table_name='project_ingestion_keys')
    op.drop_index(op.f('ix_project_ingestion_keys_deleted_at'), table_name='project_ingestion_keys')
    op.drop_index(op.f('ix_project_ingestion_keys_created_by_account_id'), table_name='project_ingestion_keys')
    op.drop_index(op.f('ix_project_ingestion_keys_created_at'), table_name='project_ingestion_keys')
    op.drop_table('project_ingestion_keys')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_project_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_deleted_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_joined_at'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_deleted_at'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_created_at'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_account_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_teams_status'), table_name='teams')
    op.drop_index(op.f('ix_teams_deleted_at'), table_name='teams')
    op.drop_index(op.f('ix_teams_created_at'), table_name='teams')
    op.drop_index(op.f('ix_teams_account_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_deleted_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_created_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_accounts_deleted_at'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
