"""empty message

Revision ID: cfc2918bafc0
Revises: 7f41c03ee0de
Create Date: 2026-08-14 12:08:05.342650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc2918bafc0'
down_revision: Union[str, Sequence[str], None] = '7f41c03ee0de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
