/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        "on-background": "#dae2fd",

        surface: "#0b1326",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-variant": "#2d3449",

        "on-surface": "#dae2fd",
        "on-surface-variant": "#c2c6d6",

        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",

        outline: "#8c909f",
        "outline-variant": "#424754",
        "surface-tint": "#adc6ff",

        primary: "#adc6ff",
        "on-primary": "#002e6a",
        "primary-container": "#4d8eff",
        "on-primary-container": "#00285d",
        "inverse-primary": "#005ac2",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",

        secondary: "#c0c1ff",
        "on-secondary": "#1000a9",
        "secondary-container": "#3131c0",
        "on-secondary-container": "#b0b2ff",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed": "#07006c",
        "on-secondary-fixed-variant": "#2f2ebe",

        tertiary: "#ffb786",
        "on-tertiary": "#502400",
        "tertiary-container": "#df7412",
        "on-tertiary-container": "#461f00",
        "tertiary-fixed": "#ffdcc6",
        "tertiary-fixed-dim": "#ffb786",
        "on-tertiary-fixed": "#311400",
        "on-tertiary-fixed-variant": "#723600",

        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",

        success: {
          DEFAULT: "#4ade80",
          bg: "rgba(74, 222, 128, 0.12)",
        },
        warning: {
          DEFAULT: "#ffb786",
          bg: "rgba(223, 116, 18, 0.15)",
        },
        info: {
          DEFAULT: "#adc6ff",
          bg: "rgba(77, 142, 255, 0.15)",
        },

        "log-error-bg": "rgba(147, 0, 10, 0.15)",
        "log-error-text": "#ffb4ab",
        "log-warn-bg": "rgba(223, 116, 18, 0.15)",
        "log-warn-text": "#ffb786",
        "log-info-bg": "rgba(77, 142, 255, 0.15)",
        "log-info-text": "#adc6ff",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        geist: ["Geist", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["Geist"],
        "headline-lg": ["Geist"],
        "code-md": ["JetBrains Mono"],
        "code-sm": ["JetBrains Mono"],
        "label-caps": ["Inter"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-md": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        gutter: "12px",
        "container-padding": "24px",
        "sidebar-width": "240px",
        "topbar-height": "56px",
        "table-row-height": "36px",
      },
      boxShadow: {
        overlay: "0 4px 20px rgba(0, 0, 0, 0.5)",
        modal: "0 8px 40px rgba(0, 0, 0, 0.6)",
      },
    },
  },
  plugins: [],
};
